-- Campaign Ledger setup for the Supabase SQL editor.

-- Generated by:  python migrate.py --sql   (regenerate after adding migrations).

-- Safe to paste ONCE on an empty database; if anything fails, nothing is applied.

BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'));

-- ---- 0001_initial.sql ----

-- Campaign Ledger: initial Postgres schema.
-- Mirrors the legacy SQLite model 1:1 (same tables, columns, defaults, cascades)
-- so application behaviour is preserved.  Deliberate differences:
--   * ids are IDENTITY columns (replaces AUTOINCREMENT)
--   * REAL -> DOUBLE PRECISION (SQLite REAL is 8 bytes; Postgres REAL is only 4)
--   * created_at is a whole-second UTC timestamp (renders like SQLite's CURRENT_TIMESTAMP)
--   * every foreign key is enforced (the legacy file had none on groups/maps in old DBs)
--   * booleans stay INTEGER 0/1 and JSON stays TEXT, exactly as the app already expects
-- map_pins.participant_id intentionally has NO foreign key: the app keeps it in
-- sync itself (character pins are deleted, familiar pins are detached).

CREATE TABLE users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    created_at    TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE campaigns (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    avatar_path TEXT,
    setting     TEXT,
    status      TEXT DEFAULT 'active',
    access_mode TEXT DEFAULT 'private',
    created_at  TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE campaign_members (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    user_id     INTEGER NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
    role        TEXT DEFAULT 'owner',
    status      TEXT DEFAULT 'player',
    created_at  TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    UNIQUE (campaign_id, user_id)
);

CREATE TABLE groups (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id INTEGER REFERENCES campaigns(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    avatar_path TEXT,
    bio         TEXT,
    color       TEXT DEFAULT '#c9a24b',
    created_at  TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE characters (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id       INTEGER REFERENCES campaigns(id) ON DELETE CASCADE,
    name              TEXT NOT NULL,
    is_npc            INTEGER DEFAULT 0,
    level             INTEGER DEFAULT 1,
    max_hp            INTEGER DEFAULT 10,
    str_score         INTEGER DEFAULT 10,
    dex_score         INTEGER DEFAULT 10,
    con_score         INTEGER DEFAULT 10,
    int_score         INTEGER DEFAULT 10,
    wis_score         INTEGER DEFAULT 10,
    cha_score         INTEGER DEFAULT 10,
    armor_class       INTEGER DEFAULT 10,
    avatar_path       TEXT,
    notes             TEXT,
    group_id          INTEGER REFERENCES groups(id) ON DELETE SET NULL,
    is_temp_familiar  INTEGER DEFAULT 0,
    familiar_icon_key TEXT,
    created_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at        TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE character_sheets (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    image_path   TEXT NOT NULL,
    sort_order   INTEGER DEFAULT 0
);

CREATE TABLE battle_participants (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id   INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    display_suffix INTEGER DEFAULT 0,
    current_hp     INTEGER NOT NULL,
    initiative     INTEGER DEFAULT 0,
    ac_override    INTEGER,
    temp_hp        INTEGER DEFAULT 0,
    is_dead        INTEGER DEFAULT 0,
    sort_order     INTEGER DEFAULT 0
);

CREATE TABLE maps (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id        INTEGER REFERENCES campaigns(id) ON DELETE CASCADE,
    name               TEXT NOT NULL,
    image_path         TEXT NOT NULL,
    image_width        INTEGER DEFAULT 0,
    image_height       INTEGER DEFAULT 0,
    grid_size          INTEGER DEFAULT 50,
    grid_offset_x      INTEGER DEFAULT 0,
    grid_offset_y      INTEGER DEFAULT 0,
    grid_color         TEXT DEFAULT 'gray',
    grid_visible       INTEGER DEFAULT 1,
    grid_setup_done    INTEGER DEFAULT 0,
    snap_to_grid       INTEGER DEFAULT 0,
    linked_to_battle   INTEGER DEFAULT 0,
    locked_for_players INTEGER DEFAULT 0,
    created_at         TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE map_drawings (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id       INTEGER NOT NULL REFERENCES maps(id) ON DELETE CASCADE,
    kind         TEXT NOT NULL,                 -- 'line' | 'rect' | 'oval' | 'pen'
    data         TEXT NOT NULL,                 -- JSON text, kind-specific geometry
    cx           DOUBLE PRECISION DEFAULT 0,
    cy           DOUBLE PRECISION DEFAULT 0,
    w            DOUBLE PRECISION DEFAULT 0,
    h            DOUBLE PRECISION DEFAULT 0,
    rotation     DOUBLE PRECISION DEFAULT 0,
    color        TEXT DEFAULT '#c9a24b',
    fill         INTEGER DEFAULT 0,
    fill_opacity DOUBLE PRECISION DEFAULT 0.4,
    sort_order   INTEGER DEFAULT 0,
    locked       INTEGER DEFAULT 0
);

CREATE TABLE map_pins (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id         INTEGER NOT NULL REFERENCES maps(id) ON DELETE CASCADE,
    pin_type       TEXT NOT NULL DEFAULT 'character',   -- 'character' | 'prop'
    participant_id INTEGER,                              -- app-managed, see header
    icon_key       TEXT,
    custom_name    TEXT,
    x              DOUBLE PRECISION NOT NULL,
    y              DOUBLE PRECISION NOT NULL,
    scale          DOUBLE PRECISION DEFAULT 1.0,
    rotation       DOUBLE PRECISION DEFAULT 0,
    locked         INTEGER DEFAULT 0
);

CREATE INDEX idx_campaign_members_campaign ON campaign_members(campaign_id);
CREATE INDEX idx_campaign_members_user     ON campaign_members(user_id);
CREATE INDEX idx_groups_campaign           ON groups(campaign_id);
CREATE INDEX idx_characters_campaign       ON characters(campaign_id);
CREATE INDEX idx_characters_group          ON characters(group_id);
CREATE INDEX idx_characters_created_by     ON characters(created_by);
CREATE INDEX idx_sheets_character          ON character_sheets(character_id);
CREATE INDEX idx_battle_character          ON battle_participants(character_id);
CREATE INDEX idx_maps_campaign             ON maps(campaign_id);
CREATE INDEX idx_drawings_map              ON map_drawings(map_id);
CREATE INDEX idx_pins_map                  ON map_pins(map_id);
CREATE INDEX idx_pins_participant          ON map_pins(participant_id);

INSERT INTO schema_migrations (version) VALUES ('0001_initial.sql');

-- ---- 0002_lock_down_data_api.sql ----

-- Lock the application tables away from Supabase's public REST/GraphQL Data API.
--
-- Supabase exposes every table in the `public` schema to the `anon` and
-- `authenticated` roles unless Row Level Security is enabled.  This app never
-- uses that API: the Flask server connects straight to Postgres as the table
-- owner (which bypasses RLS).  So:
--   * enable RLS on every table with NO policies  -> API roles see nothing
--   * revoke the API roles' privileges            -> defence in depth
--   * stop future tables inheriting those grants
-- On a plain Postgres server (no anon/authenticated roles) only the RLS part
-- applies, which is harmless for the owner role the app uses.
DO $$
DECLARE
    t record;
BEGIN
    FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t.tablename);
    END LOOP;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON ALL TABLES    IN SCHEMA public FROM anon;
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
        REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM anon;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES    FROM anon;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM anon;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON ALL TABLES    IN SCHEMA public FROM authenticated;
        REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated;
        REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM authenticated;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES    FROM authenticated;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM authenticated;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM authenticated;
    END IF;
END
$$;

INSERT INTO schema_migrations (version) VALUES ('0002_lock_down_data_api.sql');

-- ---- 0003_auth_throttle.sql ----

-- Brute-force protection for login and registration.
-- Stored in the database (not in memory) because a serverless deployment runs many
-- separate app instances that share nothing else.  Keys are HMACs of the username /
-- IP address, never the raw values.
CREATE TABLE login_attempts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       TEXT NOT NULL,        -- login-pair | login-user | login-ip | register-ip
    key        TEXT NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
CREATE INDEX idx_login_attempts_lookup ON login_attempts (kind, key, created_at);

-- same lock-down as every other table (see 0002): closed to Supabase's public Data API
ALTER TABLE login_attempts ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON TABLE login_attempts FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON TABLE login_attempts FROM authenticated;
    END IF;
END
$$;

INSERT INTO schema_migrations (version) VALUES ('0003_auth_throttle.sql');

-- ---- 0004_public_ids.sql ----

-- Add stable, host-portable public identifiers to the four entities the app
-- addresses directly by id in routes and exports: campaigns, characters,
-- groups and maps. These are not used to replace the internal integer ids
-- yet (no route or query changes here) -- they exist so a later change (e.g.
-- exposing IDs in URLs or across a host migration) never has to invent them
-- retroactively or touch historical data.
--
-- gen_random_uuid() is a Postgres core function since version 13 (no
-- pgcrypto/uuid-ossp extension required). ADD COLUMN with this default
-- rewrites the table once, assigning every existing row its own random UUID;
-- new rows get one automatically on insert.

ALTER TABLE campaigns  ADD COLUMN public_id UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE characters ADD COLUMN public_id UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE groups     ADD COLUMN public_id UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE maps       ADD COLUMN public_id UUID NOT NULL DEFAULT gen_random_uuid();

CREATE UNIQUE INDEX idx_campaigns_public_id  ON campaigns(public_id);
CREATE UNIQUE INDEX idx_characters_public_id ON characters(public_id);
CREATE UNIQUE INDEX idx_groups_public_id     ON groups(public_id);
CREATE UNIQUE INDEX idx_maps_public_id       ON maps(public_id);

INSERT INTO schema_migrations (version) VALUES ('0004_public_ids.sql');

-- ---- 0005_case_insensitive_usernames.sql ----

-- Usernames become case-insensitive: 'Bob' and 'bob' are the same account from here on.
-- Display case is preserved (we don't rewrite anyone's stored username) -- only lookups and
-- the uniqueness check become case-insensitive.
--
-- Guard first: if two existing accounts already differ only by case (not possible today since
-- the column has always been case-sensitive-unique, but this migration must still be safe to
-- run against any real, possibly-messy production data), refuse to proceed with a clear error
-- naming them, rather than let CREATE UNIQUE INDEX fail with an opaque constraint violation or
-- -- worse -- silently pick one arbitrarily. Whoever runs this fixes the conflict by renaming
-- one of the accounts, then re-runs.
DO $$
DECLARE
    conflict RECORD;
BEGIN
    SELECT lower(username) AS lu, array_agg(username ORDER BY id) AS variants
      INTO conflict
      FROM users
      GROUP BY lower(username)
      HAVING count(*) > 1
      LIMIT 1;
    IF FOUND THEN
        RAISE EXCEPTION 'Cannot make usernames case-insensitive: % already exist as %. Rename one of them, then re-run this migration.',
            array_length(conflict.variants, 1), conflict.variants;
    END IF;
END $$;

CREATE UNIQUE INDEX idx_users_username_ci ON users (lower(username));

INSERT INTO schema_migrations (version) VALUES ('0005_case_insensitive_usernames.sql');

-- ---- 0006_map_fog.sql ----

-- Map fog of war. The mask is one bit per FOG_CELL x FOG_CELL block of the map image
-- (1 = fogged), packed row by row, zlib-compressed and base64-encoded (see fog.py).
-- NULL means "no fog". fog_version bumps on every change so open tabs know when to refetch.
ALTER TABLE maps ADD COLUMN fog_mask    TEXT;
ALTER TABLE maps ADD COLUMN fog_cols    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE maps ADD COLUMN fog_rows    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE maps ADD COLUMN fog_version INTEGER NOT NULL DEFAULT 0;

INSERT INTO schema_migrations (version) VALUES ('0006_map_fog.sql');

-- ---- 0007_battle_turns.sql ----

-- Turn tracker: which participant is acting and which round the fight is in.
-- Kept on the campaign (one battle per campaign today). battle_turn_id clears itself if that
-- participant leaves the battle.
ALTER TABLE campaigns ADD COLUMN battle_round   INTEGER NOT NULL DEFAULT 1;
ALTER TABLE campaigns ADD COLUMN battle_turn_id INTEGER REFERENCES battle_participants(id) ON DELETE SET NULL;

INSERT INTO schema_migrations (version) VALUES ('0007_battle_turns.sql');

-- ---- 0008_battle_conditions.sql ----

-- Battle conditions (Blinded, Prone, ...): kept on the participant as a comma-separated list of
-- condition keys, in a fixed order.  The allowed keys live in app.py (BATTLE_CONDITIONS).
ALTER TABLE battle_participants ADD COLUMN conditions TEXT NOT NULL DEFAULT '';

INSERT INTO schema_migrations (version) VALUES ('0008_battle_conditions.sql');

-- ---- 0009_character_class.sql ----

-- Optional character class (one of the 13 keys listed in app.py, CHARACTER_CLASSES).
-- Unknown values are rejected by the app; the column itself stays free text so adding a class never needs a migration.
ALTER TABLE characters ADD COLUMN class_key TEXT;

INSERT INTO schema_migrations (version) VALUES ('0009_character_class.sql');

-- ---- 0010_invitations_notifications.sql ----

-- Campaign invitations (accept / decline) and a general in-app notification system.
--
-- Inviting a user no longer adds them to the campaign.  It creates a PENDING invitation and a
-- notification; the invited user joins only when they accept.  Notifications are generic
-- (kind + title + body + optional link), so future features can reuse them.

CREATE TABLE campaign_invitations (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id     INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    invited_user_id INTEGER NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
    invited_by_id   INTEGER          REFERENCES users(id)     ON DELETE SET NULL,
    status          TEXT NOT NULL DEFAULT 'player',          -- in-game status they get on joining: dm | player
    state           TEXT NOT NULL DEFAULT 'pending',         -- pending | accepted | declined | revoked
    created_at      TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    responded_at    TIMESTAMP(0)
);
-- at most one open invitation per person per campaign (re-inviting after a decline is fine)
CREATE UNIQUE INDEX uq_campaign_invitations_pending ON campaign_invitations (campaign_id, invited_user_id) WHERE state = 'pending';
CREATE INDEX idx_campaign_invitations_user ON campaign_invitations (invited_user_id, state);

CREATE TABLE notifications (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind          TEXT NOT NULL,                              -- campaign_invite | invite_accepted | invite_declined | ...
    title         TEXT NOT NULL,
    body          TEXT NOT NULL DEFAULT '',
    link          TEXT,                                       -- optional in-app path
    invitation_id INTEGER REFERENCES campaign_invitations(id) ON DELETE CASCADE,
    created_at    TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    read_at       TIMESTAMP(0)
);
CREATE INDEX idx_notifications_user ON notifications (user_id, read_at, id);

-- same lock-down as every other table (see 0002): closed to Supabase's public Data API
ALTER TABLE campaign_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON TABLE campaign_invitations, notifications FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON TABLE campaign_invitations, notifications FROM authenticated;
    END IF;
END
$$;

INSERT INTO schema_migrations (version) VALUES ('0010_invitations_notifications.sql');

-- ---- 0011_invite_links.sql ----

-- Campaign invite links: an opaque token the owner shares; anyone logged in who opens it can join as a Player.
-- Only a hash of the token is stored (the link is shown once, at creation), links expire, can be capped
-- to a number of uses, and can be revoked.  They work only while the campaign's access mode is "invite_link".
CREATE TABLE campaign_invite_links (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id   INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    created_by_id INTEGER          REFERENCES users(id)     ON DELETE SET NULL,
    token_hash    TEXT NOT NULL UNIQUE,                       -- sha256 hex of the token
    created_at    TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    expires_at    TIMESTAMP(0) NOT NULL,
    max_uses      INTEGER,                                    -- NULL = unlimited
    use_count     INTEGER NOT NULL DEFAULT 0,
    revoked_at    TIMESTAMP(0)
);
CREATE INDEX idx_campaign_invite_links_campaign ON campaign_invite_links (campaign_id, id);

-- same lock-down as every other table (see 0002): closed to Supabase's public Data API
ALTER TABLE campaign_invite_links ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON TABLE campaign_invite_links FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON TABLE campaign_invite_links FROM authenticated;
    END IF;
END
$$;

INSERT INTO schema_migrations (version) VALUES ('0011_invite_links.sql');

-- ---- 0012_custom_conditions.sql ----

-- Custom battle conditions: up to three free-text conditions per participant, typed by the DM
-- (the standard ones live in battle_participants.conditions as fixed keys).  Stored as a JSON array of strings.
ALTER TABLE battle_participants ADD COLUMN custom_conditions TEXT NOT NULL DEFAULT '[]';

INSERT INTO schema_migrations (version) VALUES ('0012_custom_conditions.sql');

-- ---- 0013_map_character_pins.sql ----

-- Characters on the map no longer depend on the battle: a character pin now remembers WHICH character it shows
-- (character_id), and its battle row (participant_id) is only filled in while the map is linked to the battle.
ALTER TABLE map_pins ADD COLUMN character_id INTEGER REFERENCES characters(id) ON DELETE CASCADE;

UPDATE map_pins SET character_id = (SELECT bp.character_id FROM battle_participants bp WHERE bp.id = map_pins.participant_id)
 WHERE pin_type = 'character' AND participant_id IS NOT NULL;
DELETE FROM map_pins WHERE pin_type = 'character' AND character_id IS NULL;   -- orphans of removed battle rows

-- Maps that are not linked keep their character pins as plain map tokens (no battle row behind them).
UPDATE map_pins SET participant_id = NULL
 WHERE pin_type = 'character' AND map_id IN (SELECT id FROM maps WHERE linked_to_battle = 0);

CREATE INDEX idx_map_pins_character ON map_pins(character_id);
-- One token per battle row per map, so two clients syncing at once can never double-place someone.
CREATE UNIQUE INDEX uq_map_pins_participant ON map_pins(map_id, participant_id)
 WHERE pin_type = 'character' AND participant_id IS NOT NULL;

INSERT INTO schema_migrations (version) VALUES ('0013_map_character_pins.sql');

COMMIT;
