-- Campaign Ledger: initial Postgres schema.
-- Mirrors the legacy SQLite model 1:1 (same tables, columns, defaults, cascades)
-- so application behaviour is preserved.  Deliberate differences:
--   * ids are IDENTITY columns (replaces AUTOINCREMENT)
--   * REAL -> DOUBLE PRECISION (SQLite REAL is 8 bytes; Postgres REAL is only 4)
--   * created_at is a whole-second UTC timestamp (renders like SQLite's CURRENT_TIMESTAMP)
--   * every foreign key is enforced (the legacy file had none on groups/maps in old DBs)
--   * booleans stay INTEGER 0/1 and JSON stays TEXT, exactly as the app already expects
-- map_pins.participant_id intentionally has NO foreign key: the app keeps it in
-- sync itself (character pins are deleted, familiar pins are detached).

CREATE TABLE users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    created_at    TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE campaigns (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    avatar_path TEXT,
    setting     TEXT,
    status      TEXT DEFAULT 'active',
    access_mode TEXT DEFAULT 'private',
    created_at  TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE campaign_members (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    user_id     INTEGER NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
    role        TEXT DEFAULT 'owner',
    status      TEXT DEFAULT 'player',
    created_at  TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    UNIQUE (campaign_id, user_id)
);

CREATE TABLE groups (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id INTEGER REFERENCES campaigns(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    avatar_path TEXT,
    bio         TEXT,
    color       TEXT DEFAULT '#c9a24b',
    created_at  TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE characters (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id       INTEGER REFERENCES campaigns(id) ON DELETE CASCADE,
    name              TEXT NOT NULL,
    is_npc            INTEGER DEFAULT 0,
    level             INTEGER DEFAULT 1,
    max_hp            INTEGER DEFAULT 10,
    str_score         INTEGER DEFAULT 10,
    dex_score         INTEGER DEFAULT 10,
    con_score         INTEGER DEFAULT 10,
    int_score         INTEGER DEFAULT 10,
    wis_score         INTEGER DEFAULT 10,
    cha_score         INTEGER DEFAULT 10,
    armor_class       INTEGER DEFAULT 10,
    avatar_path       TEXT,
    notes             TEXT,
    group_id          INTEGER REFERENCES groups(id) ON DELETE SET NULL,
    is_temp_familiar  INTEGER DEFAULT 0,
    familiar_icon_key TEXT,
    created_by        INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at        TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE character_sheets (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    image_path   TEXT NOT NULL,
    sort_order   INTEGER DEFAULT 0
);

CREATE TABLE battle_participants (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id   INTEGER NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    display_suffix INTEGER DEFAULT 0,
    current_hp     INTEGER NOT NULL,
    initiative     INTEGER DEFAULT 0,
    ac_override    INTEGER,
    temp_hp        INTEGER DEFAULT 0,
    is_dead        INTEGER DEFAULT 0,
    sort_order     INTEGER DEFAULT 0
);

CREATE TABLE maps (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id        INTEGER REFERENCES campaigns(id) ON DELETE CASCADE,
    name               TEXT NOT NULL,
    image_path         TEXT NOT NULL,
    image_width        INTEGER DEFAULT 0,
    image_height       INTEGER DEFAULT 0,
    grid_size          INTEGER DEFAULT 50,
    grid_offset_x      INTEGER DEFAULT 0,
    grid_offset_y      INTEGER DEFAULT 0,
    grid_color         TEXT DEFAULT 'gray',
    grid_visible       INTEGER DEFAULT 1,
    grid_setup_done    INTEGER DEFAULT 0,
    snap_to_grid       INTEGER DEFAULT 0,
    linked_to_battle   INTEGER DEFAULT 0,
    locked_for_players INTEGER DEFAULT 0,
    created_at         TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE map_drawings (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id       INTEGER NOT NULL REFERENCES maps(id) ON DELETE CASCADE,
    kind         TEXT NOT NULL,                 -- 'line' | 'rect' | 'oval' | 'pen'
    data         TEXT NOT NULL,                 -- JSON text, kind-specific geometry
    cx           DOUBLE PRECISION DEFAULT 0,
    cy           DOUBLE PRECISION DEFAULT 0,
    w            DOUBLE PRECISION DEFAULT 0,
    h            DOUBLE PRECISION DEFAULT 0,
    rotation     DOUBLE PRECISION DEFAULT 0,
    color        TEXT DEFAULT '#c9a24b',
    fill         INTEGER DEFAULT 0,
    fill_opacity DOUBLE PRECISION DEFAULT 0.4,
    sort_order   INTEGER DEFAULT 0,
    locked       INTEGER DEFAULT 0
);

CREATE TABLE map_pins (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id         INTEGER NOT NULL REFERENCES maps(id) ON DELETE CASCADE,
    pin_type       TEXT NOT NULL DEFAULT 'character',   -- 'character' | 'prop'
    participant_id INTEGER,                              -- app-managed, see header
    icon_key       TEXT,
    custom_name    TEXT,
    x              DOUBLE PRECISION NOT NULL,
    y              DOUBLE PRECISION NOT NULL,
    scale          DOUBLE PRECISION DEFAULT 1.0,
    rotation       DOUBLE PRECISION DEFAULT 0,
    locked         INTEGER DEFAULT 0
);

CREATE INDEX idx_campaign_members_campaign ON campaign_members(campaign_id);
CREATE INDEX idx_campaign_members_user     ON campaign_members(user_id);
CREATE INDEX idx_groups_campaign           ON groups(campaign_id);
CREATE INDEX idx_characters_campaign       ON characters(campaign_id);
CREATE INDEX idx_characters_group          ON characters(group_id);
CREATE INDEX idx_characters_created_by     ON characters(created_by);
CREATE INDEX idx_sheets_character          ON character_sheets(character_id);
CREATE INDEX idx_battle_character          ON battle_participants(character_id);
CREATE INDEX idx_maps_campaign             ON maps(campaign_id);
CREATE INDEX idx_drawings_map              ON map_drawings(map_id);
CREATE INDEX idx_pins_map                  ON map_pins(map_id);
CREATE INDEX idx_pins_participant          ON map_pins(participant_id);
