-- Brute-force protection for login and registration.
-- Stored in the database (not in memory) because a serverless deployment runs many
-- separate app instances that share nothing else.  Keys are HMACs of the username /
-- IP address, never the raw values.
CREATE TABLE login_attempts (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       TEXT NOT NULL,        -- login-pair | login-user | login-ip | register-ip
    key        TEXT NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
CREATE INDEX idx_login_attempts_lookup ON login_attempts (kind, key, created_at);

-- same lock-down as every other table (see 0002): closed to Supabase's public Data API
ALTER TABLE login_attempts ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON TABLE login_attempts FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON TABLE login_attempts FROM authenticated;
    END IF;
END
$$;
