-- Campaign invitations (accept / decline) and a general in-app notification system.
--
-- Inviting a user no longer adds them to the campaign.  It creates a PENDING invitation and a
-- notification; the invited user joins only when they accept.  Notifications are generic
-- (kind + title + body + optional link), so future features can reuse them.

CREATE TABLE campaign_invitations (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id     INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    invited_user_id INTEGER NOT NULL REFERENCES users(id)     ON DELETE CASCADE,
    invited_by_id   INTEGER          REFERENCES users(id)     ON DELETE SET NULL,
    status          TEXT NOT NULL DEFAULT 'player',          -- in-game status they get on joining: dm | player
    state           TEXT NOT NULL DEFAULT 'pending',         -- pending | accepted | declined | revoked
    created_at      TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    responded_at    TIMESTAMP(0)
);
-- at most one open invitation per person per campaign (re-inviting after a decline is fine)
CREATE UNIQUE INDEX uq_campaign_invitations_pending ON campaign_invitations (campaign_id, invited_user_id) WHERE state = 'pending';
CREATE INDEX idx_campaign_invitations_user ON campaign_invitations (invited_user_id, state);

CREATE TABLE notifications (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind          TEXT NOT NULL,                              -- campaign_invite | invite_accepted | invite_declined | ...
    title         TEXT NOT NULL,
    body          TEXT NOT NULL DEFAULT '',
    link          TEXT,                                       -- optional in-app path
    invitation_id INTEGER REFERENCES campaign_invitations(id) ON DELETE CASCADE,
    created_at    TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    read_at       TIMESTAMP(0)
);
CREATE INDEX idx_notifications_user ON notifications (user_id, read_at, id);

-- same lock-down as every other table (see 0002): closed to Supabase's public Data API
ALTER TABLE campaign_invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON TABLE campaign_invitations, notifications FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON TABLE campaign_invitations, notifications FROM authenticated;
    END IF;
END
$$;
