-- Campaign invite links: an opaque token the owner shares; anyone logged in who opens it can join as a Player.
-- Only a hash of the token is stored (the link is shown once, at creation), links expire, can be capped
-- to a number of uses, and can be revoked.  They work only while the campaign's access mode is "invite_link".
CREATE TABLE campaign_invite_links (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id   INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    created_by_id INTEGER          REFERENCES users(id)     ON DELETE SET NULL,
    token_hash    TEXT NOT NULL UNIQUE,                       -- sha256 hex of the token
    created_at    TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    expires_at    TIMESTAMP(0) NOT NULL,
    max_uses      INTEGER,                                    -- NULL = unlimited
    use_count     INTEGER NOT NULL DEFAULT 0,
    revoked_at    TIMESTAMP(0)
);
CREATE INDEX idx_campaign_invite_links_campaign ON campaign_invite_links (campaign_id, id);

-- same lock-down as every other table (see 0002): closed to Supabase's public Data API
ALTER TABLE campaign_invite_links ENABLE ROW LEVEL SECURITY;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON TABLE campaign_invite_links FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON TABLE campaign_invite_links FROM authenticated;
    END IF;
END
$$;
