-- Every roll made through the app is recorded, so the whole campaign sees it (a toast on whatever page they are on)
-- and the roll log has something to read later.  "private" rolls are the DM's own and only DMs are sent them.
CREATE TABLE dice_rolls (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id  INTEGER NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
    user_id      INTEGER REFERENCES users(id) ON DELETE SET NULL,
    character_id INTEGER REFERENCES characters(id) ON DELETE SET NULL,
    label        TEXT NOT NULL DEFAULT '',
    dice         TEXT NOT NULL,                                  -- JSON: [{"sides": 20, "value": 14, "dropped": false}, ...]
    modifier     INTEGER NOT NULL DEFAULT 0,
    total        INTEGER NOT NULL,
    mode         TEXT NOT NULL DEFAULT 'normal',                 -- normal | advantage | disadvantage
    private      INTEGER NOT NULL DEFAULT 0,
    created_at   TIMESTAMP(0) NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);
CREATE INDEX idx_dice_rolls_campaign ON dice_rolls (campaign_id, id);

ALTER TABLE dice_rolls ENABLE ROW LEVEL SECURITY;               -- like every table: no direct access through Supabase's data API
